server:
  port: 8080
  forward-headers-strategy: FRAMEWORK
  shutdown: graceful
  error:
    include-exception: off
    include-stacktrace: never
    include-message: never

spring:
  profiles:
    active: default
  config:
    import:
      - classpath:config/common.yaml
      - classpath:config/postgres.yaml
      - classpath:config/axon.yaml

  application:
    name:  kboot-postgres
